language: cpp
compiler: gcc
os: linux



before_install:
  - sudo apt-get update -qq
#  - sudo apt-get install libsfml-dev

before_script:
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DSFML_ROOT="deps/SFML/installation" .

install:
    - sudo apt-get install libglew-dev
    - sudo apt-get install libopenal-dev
    - sudo apt-get install libsndfile-dev
    - sudo apt-get install libx11-dev
    - sudo apt-get install freeglut3-dev
    - sudo apt-get install libjpeg-dev
    - sudo apt-get install libfreetype6-dev
    - sudo apt-get install libxrandr-dev
    - sudo apt-get install libx11-xcb-dev


    - cd deps/SFML && mkdir build && cd build
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX=../installation ../
    - make install
    - cd ../../..

script:
    - make

after_script:
    - true

#branches:
#  only:
#    - master

notifications:
    email: false
