language: cpp
compiler: gcc
os: linux



before_install:
  - sudo apt-get update -qq
# - sudo apt-get install libsfml-dev
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  # gcc
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9


before_script:
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DSFML_ROOT="deps/SFML/installation" .

install:
    - sudo apt-get install libglew-dev
    - sudo apt-get install libopenal-dev
    - sudo apt-get install libsndfile-dev
    - sudo apt-get install libx11-dev
    - sudo apt-get install freeglut3-dev
    - sudo apt-get install libjpeg-dev
    - sudo apt-get install libfreetype6-dev
    - sudo apt-get install libxrandr-dev
    - sudo apt-get install libx11-xcb-dev
    - sudo apt-get install libxcb-image0-dev 
    - sudo apt-get install libxcb-randr0-dev
    - sudo apt-get install libudev-dev 
    - cd deps/SFML && mkdir build && cd build
    - cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=1 -DCMAKE_INSTALL_PREFIX=../installation ../
    - make -j8 && make install
    - cd ../../..
    
    
    - sudo apt-get install libgtest-dev
    - pushd /usr/src/gtest
    - sudo cmake .
    - sudo make 
    - sudo mv lib* /usr/lib/
    - popd
    

script:
    - make

after_script:
    - true

branches:
  only:
    - master

notifications:
    email: false
